HOSPITALS = [
    {'id': 'hsp-bjxh', 'name': '北京协和医院', 'region': '华北', 'level': '三甲'},
    {'id': 'hsp-bj301', 'name': '中国人民解放军总医院', 'region': '华北', 'level': '三甲'},
    {'id': 'hsp-bjyt', 'name': '北京医院', 'region': '华北', 'level': '三甲'},
    {'id': 'hsp-bjty', 'name': '北京天坛医院', 'region': '华北', 'level': '三甲'},
    {'id': 'hsp-bjax', 'name': '北京安贞医院', 'region': '华北', 'level': '三甲'},
    {'id': 'hsp-bjzy', 'name': '中日友好医院', 'region': '华北', 'level': '三甲'},
    {'id': 'hsp-tjjh', 'name': '天津医科大学总医院', 'region': '华北', 'level': '三甲'},
    {'id': 'hsp-sjz1', 'name': '河北医科大学第二医院', 'region': '华北', 'level': '三甲'},
    {'id': 'hsp-shruj', 'name': '上海交通大学医学院附属瑞金医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-shrh', 'name': '复旦大学附属中山医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-shhy', 'name': '复旦大学附属华山医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-shlc', 'name': '上海长征医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-shlh', 'name': '上海中医药大学附属龙华医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-njdr', 'name': '南京鼓楼医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-njsl', 'name': '江苏省人民医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-hzzy', 'name': '浙江大学医学院附属第一医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-hzse', 'name': '浙江大学医学院附属第二医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-hfyk', 'name': '中国科学技术大学附属第一医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-xm1', 'name': '厦门大学附属第一医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-jnql', 'name': '山东大学齐鲁医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-whzn', 'name': '武汉大学中南医院', 'region': '华中', 'level': '三甲'},
    {'id': 'hsp-whxt', 'name': '华中科技大学同济医学院附属协和医院', 'region': '华中', 'level': '三甲'},
    {'id': 'hsp-whtj', 'name': '华中科技大学同济医学院附属同济医院', 'region': '华中', 'level': '三甲'},
    {'id': 'hsp-csxy', 'name': '中南大学湘雅医院', 'region': '华中', 'level': '三甲'},
    {'id': 'hsp-csxe', 'name': '中南大学湘雅二医院', 'region': '华中', 'level': '三甲'},
    {'id': 'hsp-zzdx', 'name': '郑州大学第一附属医院', 'region': '华中', 'level': '三甲'},
    {'id': 'hsp-nc1', 'name': '南昌大学第一附属医院', 'region': '华中', 'level': '三甲'},
    {'id': 'hsp-gzfy', 'name': '广州医科大学附属第一医院', 'region': '华南', 'level': '三甲'},
    {'id': 'hsp-gzzy', 'name': '中山大学附属第一医院', 'region': '华南', 'level': '三甲'},
    {'id': 'hsp-gzzs6', 'name': '中山大学附属第六医院', 'region': '华南', 'level': '三甲'},
    {'id': 'hsp-szrm', 'name': '深圳市人民医院', 'region': '华南', 'level': '三甲'},
    {'id': 'hsp-sz2', 'name': '深圳大学总医院', 'region': '华南', 'level': '三甲'},
    {'id': 'hsp-nn1', 'name': '广西医科大学第一附属医院', 'region': '华南', 'level': '三甲'},
    {'id': 'hsp-ha1', 'name': '海南医学院第一附属医院', 'region': '华南', 'level': '三甲'},
    {'id': 'hsp-cqzl', 'name': '重庆市肿瘤医院', 'region': '西南', 'level': '三甲'},
    {'id': 'hsp-cqdr', 'name': '重庆医科大学附属第一医院', 'region': '西南', 'level': '三甲'},
    {'id': 'hsp-cdhx', 'name': '四川大学华西医院', 'region': '西南', 'level': '三甲'},
    {'id': 'hsp-cd2', 'name': '四川省人民医院', 'region': '西南', 'level': '三甲'},
    {'id': 'hsp-km1', 'name': '昆明医科大学第一附属医院', 'region': '西南', 'level': '三甲'},
    {'id': 'hsp-gy1', 'name': '贵州医科大学附属医院', 'region': '西南', 'level': '三甲'},
    {'id': 'hsp-xajt1', 'name': '西安交通大学第一附属医院', 'region': '西北', 'level': '三甲'},
    {'id': 'hsp-xajd2', 'name': '西安交通大学第二附属医院', 'region': '西北', 'level': '三甲'},
    {'id': 'hsp-lzdx', 'name': '兰州大学第一医院', 'region': '西北', 'level': '三甲'},
    {'id': 'hsp-xjyy', 'name': '新疆医科大学第一附属医院', 'region': '西北', 'level': '三甲'},
    {'id': 'hsp-ning1', 'name': '宁夏医科大学总医院', 'region': '西北', 'level': '三甲'},
    {'id': 'hsp-bjsy', 'name': '北京大学第三医院', 'region': '华北', 'level': '三甲'},
    {'id': 'hsp-bjxw', 'name': '宣武医院', 'region': '华北', 'level': '三甲'},
    {'id': 'hsp-sxty', 'name': '山西白求恩医院', 'region': '华北', 'level': '三甲'},
    {'id': 'hsp-nmgfy', 'name': '内蒙古医科大学附属医院', 'region': '华北', 'level': '三甲'},
    {'id': 'hsp-shrj', 'name': '上海交通大学医学院附属仁济医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-sh9y', 'name': '上海第九人民医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-zjsyf', 'name': '浙江大学医学院附属邵逸夫医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-fjxl', 'name': '福建医科大学附属协和医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-sdsy', 'name': '山东省立医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-hnrm', 'name': '河南省人民医院', 'region': '华中', 'level': '三甲'},
    {'id': 'hsp-xy3', 'name': '中南大学湘雅三医院', 'region': '华中', 'level': '三甲'},
    {'id': 'hsp-jxsl', 'name': '江西省人民医院', 'region': '华中', 'level': '三甲'},
    {'id': 'hsp-gdnf', 'name': '南方医科大学南方医院', 'region': '华南', 'level': '三甲'},
    {'id': 'hsp-gdpr', 'name': '广东省人民医院', 'region': '华南', 'level': '三甲'},
    {'id': 'hsp-gxrm', 'name': '广西壮族自治区人民医院', 'region': '华南', 'level': '三甲'},
    {'id': 'hsp-sczl', 'name': '四川省肿瘤医院', 'region': '西南', 'level': '三甲'},
    {'id': 'hsp-ynzl', 'name': '云南省肿瘤医院', 'region': '西南', 'level': '三甲'},
    {'id': 'hsp-gzrm', 'name': '贵州省人民医院', 'region': '西南', 'level': '三甲'},
    {'id': 'hsp-qhfy', 'name': '青海大学附属医院', 'region': '西北', 'level': '三甲'},
]

DEVICES = [
    {
        'id': 'dev-ctnav-pro',
        'product_line_id': 'robot',
        'product_line_name': 'CT引导下穿刺导航机器人',
        'model_name': 'CT-Nav Pro 导航机器人',
        'category': '穿刺导航机器人',
        'sn_prefix': 'CTN',
        'parameter_schema': [
            {'key': 'plannedDepth', 'label': '计划进针深度', 'unit': 'mm'},
            {'key': 'needleAngle', 'label': '进针角度', 'unit': '°'},
            {'key': 'scanCount', 'label': '扫描次数', 'unit': '次'},
        ],
        'default_consumables': ['定位针', '穿刺针', '导向架'],
    },
    {
        'id': 'dev-ire-2000',
        'product_line_id': 'ire',
        'product_line_name': 'IRE陡脉冲治疗系统',
        'model_name': 'IRE-2000 陡脉冲治疗系统',
        'category': 'IRE',
        'sn_prefix': 'IRE',
        'parameter_schema': [
            {'key': 'outputPower', 'label': '输出功率', 'unit': 'W'},
            {'key': 'pulseCount', 'label': '脉冲次数', 'unit': '次'},
            {'key': 'duration', 'label': '作用时长', 'unit': 'min'},
        ],
        'default_consumables': ['IRE 电极针', '连接线', '一次性无菌罩'],
    },
    {
        'id': 'dev-rf-90',
        'product_line_id': 'rf-ablation',
        'product_line_name': '射频消融治疗系统',
        'model_name': 'RF-90 射频消融主机',
        'category': '射频消融',
        'sn_prefix': 'RF',
        'parameter_schema': [
            {'key': 'outputPower', 'label': '输出功率', 'unit': 'W'},
            {'key': 'targetTemp', 'label': '靶温', 'unit': '°C'},
            {'key': 'duration', 'label': '维持时长', 'unit': 's'},
        ],
        'default_consumables': ['射频针', '对极板', '连接导线'],
    },
    {
        'id': 'dev-biopsy-core',
        'product_line_id': 'biopsy',
        'product_line_name': '活检穿刺系统',
        'model_name': 'CoreBx 活检穿刺系统',
        'category': '活检穿刺',
        'sn_prefix': 'CBX',
        'parameter_schema': [
            {'key': 'needleGauge', 'label': '针径规格', 'unit': 'G'},
            {'key': 'sampleCount', 'label': '取样次数', 'unit': '次'},
            {'key': 'depth', 'label': '穿刺深度', 'unit': 'mm'},
        ],
        'default_consumables': ['活检针', '同轴针', '标本盒'],
    },
    {
        'id': 'dev-vein-close',
        'product_line_id': 'vein-rf',
        'product_line_name': '静脉射频腔内闭合系统',
        'model_name': 'VeinClose 静脉闭合系统',
        'category': '静脉射频',
        'sn_prefix': 'VCL',
        'parameter_schema': [
            {'key': 'segmentLength', 'label': '闭合段长', 'unit': 'cm'},
            {'key': 'cycleCount', 'label': '闭合周期', 'unit': '次'},
            {'key': 'targetTemp', 'label': '工作温度', 'unit': '°C'},
        ],
        'default_consumables': ['静脉闭合导管', '鞘管', '耦合剂'],
    },
    {
        'id': 'dev-es-300',
        'product_line_id': 'electrosurgical',
        'product_line_name': '高频电刀系统',
        'model_name': 'ES-300 高频电刀',
        'category': '高频电刀',
        'sn_prefix': 'ES',
        'parameter_schema': [
            {'key': 'cutPower', 'label': '切割功率', 'unit': 'W'},
            {'key': 'coagPower', 'label': '凝血功率', 'unit': 'W'},
            {'key': 'modeCount', 'label': '启用模式', 'unit': '种'},
        ],
        'default_consumables': ['电刀笔', '负极板', '脚踏开关'],
    },
    {
        'id': 'dev-neuro-therm',
        'product_line_id': 'neuro',
        'product_line_name': '神经热凝治疗系统',
        'model_name': 'NeuroTherm 神经热凝系统',
        'category': '神经热凝',
        'sn_prefix': 'NT',
        'parameter_schema': [
            {'key': 'targetTemp', 'label': '靶温', 'unit': '°C'},
            {'key': 'duration', 'label': '热凝时长', 'unit': 's'},
            {'key': 'impedance', 'label': '阻抗', 'unit': 'Ω'},
        ],
        'default_consumables': ['热凝针', '刺激电极', '定位贴片'],
    },
]
