HOSPITALS = [
    {'id': 'hsp-shzy', 'name': '上海中医药大学附属龙华医院', 'region': '华东', 'level': '三甲'},
    {'id': 'hsp-bjxt', 'name': '北京协和医院', 'region': '华北', 'level': '三甲'},
    {'id': 'hsp-gzfy', 'name': '广州医科大学附属第一医院', 'region': '华南', 'level': '三甲'},
    {'id': 'hsp-cqsw', 'name': '重庆市肿瘤医院', 'region': '西南', 'level': '三甲'},
    {'id': 'hsp-whzx', 'name': '武汉大学中南医院', 'region': '华中', 'level': '三甲'},
    {'id': 'hsp-xajd', 'name': '西安交通大学第一附属医院', 'region': '西北', 'level': '三甲'},
]

DEVICES = [
    {
        'id': 'dev-ctnav-pro',
        'product_line_id': 'robot',
        'product_line_name': 'CT引导下穿刺导航机器人',
        'model_name': 'CT-Nav Pro 导航机器人',
        'category': '穿刺导航机器人',
        'sn_prefix': 'CTN',
        'parameter_schema': [
            {'key': 'plannedDepth', 'label': '计划进针深度', 'unit': 'mm'},
            {'key': 'needleAngle', 'label': '进针角度', 'unit': '°'},
            {'key': 'scanCount', 'label': '扫描次数', 'unit': '次'},
        ],
        'default_consumables': ['定位针', '穿刺针', '导向架'],
    },
    {
        'id': 'dev-ire-2000',
        'product_line_id': 'ire',
        'product_line_name': 'IRE陡脉冲治疗系统',
        'model_name': 'IRE-2000 陡脉冲治疗系统',
        'category': 'IRE',
        'sn_prefix': 'IRE',
        'parameter_schema': [
            {'key': 'outputPower', 'label': '输出功率', 'unit': 'W'},
            {'key': 'pulseCount', 'label': '脉冲次数', 'unit': '次'},
            {'key': 'duration', 'label': '作用时长', 'unit': 'min'},
        ],
        'default_consumables': ['IRE 电极针', '连接线', '一次性无菌罩'],
    },
    {
        'id': 'dev-rf-90',
        'product_line_id': 'rf-ablation',
        'product_line_name': '射频消融治疗系统',
        'model_name': 'RF-90 射频消融主机',
        'category': '射频消融',
        'sn_prefix': 'RF',
        'parameter_schema': [
            {'key': 'outputPower', 'label': '输出功率', 'unit': 'W'},
            {'key': 'targetTemp', 'label': '靶温', 'unit': '°C'},
            {'key': 'duration', 'label': '维持时长', 'unit': 's'},
        ],
        'default_consumables': ['射频针', '对极板', '连接导线'],
    },
    {
        'id': 'dev-biopsy-core',
        'product_line_id': 'biopsy',
        'product_line_name': '活检穿刺系统',
        'model_name': 'CoreBx 活检穿刺系统',
        'category': '活检穿刺',
        'sn_prefix': 'CBX',
        'parameter_schema': [
            {'key': 'needleGauge', 'label': '针径规格', 'unit': 'G'},
            {'key': 'sampleCount', 'label': '取样次数', 'unit': '次'},
            {'key': 'depth', 'label': '穿刺深度', 'unit': 'mm'},
        ],
        'default_consumables': ['活检针', '同轴针', '标本盒'],
    },
    {
        'id': 'dev-vein-close',
        'product_line_id': 'vein-rf',
        'product_line_name': '静脉射频腔内闭合系统',
        'model_name': 'VeinClose 静脉闭合系统',
        'category': '静脉射频',
        'sn_prefix': 'VCL',
        'parameter_schema': [
            {'key': 'segmentLength', 'label': '闭合段长', 'unit': 'cm'},
            {'key': 'cycleCount', 'label': '闭合周期', 'unit': '次'},
            {'key': 'targetTemp', 'label': '工作温度', 'unit': '°C'},
        ],
        'default_consumables': ['静脉闭合导管', '鞘管', '耦合剂'],
    },
    {
        'id': 'dev-es-300',
        'product_line_id': 'electrosurgical',
        'product_line_name': '高频电刀系统',
        'model_name': 'ES-300 高频电刀',
        'category': '高频电刀',
        'sn_prefix': 'ES',
        'parameter_schema': [
            {'key': 'cutPower', 'label': '切割功率', 'unit': 'W'},
            {'key': 'coagPower', 'label': '凝血功率', 'unit': 'W'},
            {'key': 'modeCount', 'label': '启用模式', 'unit': '种'},
        ],
        'default_consumables': ['电刀笔', '负极板', '脚踏开关'],
    },
    {
        'id': 'dev-neuro-therm',
        'product_line_id': 'neuro',
        'product_line_name': '神经热凝治疗系统',
        'model_name': 'NeuroTherm 神经热凝系统',
        'category': '神经热凝',
        'sn_prefix': 'NT',
        'parameter_schema': [
            {'key': 'targetTemp', 'label': '靶温', 'unit': '°C'},
            {'key': 'duration', 'label': '热凝时长', 'unit': 's'},
            {'key': 'impedance', 'label': '阻抗', 'unit': 'Ω'},
        ],
        'default_consumables': ['热凝针', '刺激电极', '定位贴片'],
    },
]
